# Generated by Django 3.1.6 on 2021-02-16 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='dateAndTime',
            field=models.DateTimeField(default=None, verbose_name=datetime.datetime(2021, 2, 16, 23, 55, 50, 14537)),
        ),
    ]
