# Generated by Django 3.1.6 on 2021-02-16 22:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_shoes_dateandtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall or Autumn', 'Fall or Autumn'), ('Winter', 'Winter')], default=1, max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('male', models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Child', 'Child')], default=1, max_length=50)),
                ('image', models.ImageField(upload_to='media')),
                ('dateAndTime', models.DateTimeField(default=None, verbose_name=datetime.datetime(2021, 2, 17, 0, 13, 42, 169589))),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.place')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.type')),
            ],
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
    ]
