# Generated by Django 3.1.6 on 2021-06-22 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210223_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='dateAndTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 17, 59, 54, 912424)),
        ),
    ]
